# kubetpl:syntax:$
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: cabot
  labels:
    service: worker
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: worker
    spec:
      containers:
      - name: worker
        image: cabotapp/cabot:${CABOT_VERSION}
        args:
        - celery
        - worker
        - -A
        - cabot
        envFrom:
        - configMapRef:
            name: cabot-default-config
        - configMapRef:
            name: cabot-${CABOT_ENVIRONMENT}-config
      restartPolicy: Always
